-- NEW VERSION --
use master
go


create database StageCOVID19
go

use StageCOVID19
go

CREATE TABLE CASESREPORT_STAGE (
    OUTCOME VARCHAR(25),
    OUTCOME_UID VARCHAR(6),
    AGE VARCHAR(35),
    AGE_UID VARCHAR(6),
    GENDER VARCHAR(15),
    GENDER_UID VARCHAR(6),
    REPORTING_PHU VARCHAR(65),
    SPECIMENDATE DATE,
    CASEREPORTED_DATE DATE,
    PHUCITY VARCHAR(25),
    TESTREPORTED_DATE DATE,
    CASEACQUISITION_INFO VARCHAR(25),
    CASEACQUISITION_INFO_UID VARCHAR(6),
    ACCURATEEPISODE_DT DATE,
    PHU_ADDRESS VARCHAR(30),
    PHU_WEBSITE VARCHAR(75),
    OUTBREAKRELATED VARCHAR(3),
    PHU_LATITUDE REAL,
    PHU_LONGITUDE REAL,
    PHU_POSTAL_CODE VARCHAR(7)
)


CREATE TABLE COMPILED_COVID19_CASE_DETAILS_CANADA_STAGE (
    ROW_ID INT,
    HEALTH_REGION VARCHAR(65),
    AGE_GROUP VARCHAR(35),
    AGE_UID VARCHAR(6),
    GENDER VARCHAR(15),
    GENDER_UID VARCHAR(6),
    EXPOSURE VARCHAR(45),
    EXPOSURE_UID VARCHAR(6),
    CASE_STATUS VARCHAR(15),
    CASE_STATUS_UID VARCHAR(6),
    DATE_REPORTED DATETIME,
    --PROVINCE VARCHAR(35),
)


CREATE TABLE ONGOING_OUTBREAKS_PHU_STAGE (
    DATE DATE,
    PHU_NUM INT,
    OUTBREAK_GROUP VARCHAR(35),
    OUTBREAK_GROUP_UID INT,
    NUMBER_ONGOING_OUTBREAKS INT
)

CREATE TABLE VACCINES_BY_AGE_PHU_STAGE (
    DATE DATE,
    PHU_ID INT,
    AGE_GROUP VARCHAR(35),
    AGE_UID VARCHAR(6),
    AT_LEAST_ONE_DOSE_CUMULATIVE INT,
    SECOND_DOSE_CUMULATIVE INT,
    FULLY_VACCINATED_CUMULATIVE INT,
    THIRD_DOSE_CUMULATIVE INT
)


CREATE TABLE PUBLIC_HEALTH_UNIT_STAGE (
    REPORTING_PHU_LATITUDE REAL,
    REPORTING_PHU_LONGITUDE REAL,
    PHU_ID INT,
    REPORTING_PHU_ADDRESS VARCHAR(40),
    REPORTING_PHU VARCHAR(65),
    REPORTING_PHU_CITY VARCHAR(25),
    REPORTING_PHU_WEBSITE VARCHAR(75),
    REPORTING_PHU_POSTAL_CODE VARCHAR(10),
)

CREATE TABLE PUBLIC_HEALTH_UNITS_GROUP_STAGE (
    PHU_GROUP VARCHAR(50),
    PHU_CITY VARCHAR(25),
    PHU_REGION VARCHAR(5),
)

use master
go