-- database for NDS
USE MASTER
GO

drop database IF EXISTS NDSCovid19
go

CREATE DATABASE NDSCovid19
GO

USE NDSCovid19
GO



CREATE TABLE SOURCE(
	SOURCE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	SOURCE_NAME VARCHAR(50) NULL,
	CREATED_DATE DATETIME NULL,
	UPDATED_DATE DATETIME NULL,
)


CREATE TABLE PHU_GROUP(
	ID INT PRIMARY KEY IDENTITY (1,1),
	GROUP_NAME VARCHAR(50),

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_GROUP_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID)
)



CREATE TABLE PHU_CITY(
	ID INT PRIMARY KEY IDENTITY (1,1),
	PHU_CITY VARCHAR(25),
	PHU_GROUP_ID INT,	--FK

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_CITY_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
	CONSTRAINT FK_PHUCITY_PHUGROUP FOREIGN KEY (PHU_GROUP_ID)
	REFERENCES PHU_GROUP(ID)
)


CREATE TABLE PUBLIC_HEALTH_UNIT(
	ID INT PRIMARY KEY IDENTITY (1,1),
	PHU_IDNK INT,
	PHU_NAME VARCHAR(65),

	PHU_ADDRESS VARCHAR(40),
	PHU_LONGITUDE REAL,
	PHU_LATITUDE REAL,
	PHU_CITY_ID INT, --FK
	PHU_POSTAL_CODE VARCHAR (10),
	PHU_WEBSITE VARCHAR(75),

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_PHU_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
	CONSTRAINT FK_PHU_CITY FOREIGN KEY (PHU_CITY_ID)
	REFERENCES PHU_CITY(ID)
)



CREATE TABLE OUTBREAK_GROUP(
	ID INT PRIMARY KEY IDENTITY (1,1),
	OUTBREAK_GROUP VARCHAR(35),
	OUTBREAK_GROUP_IDNK INT, --NK

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_OUTBREAKGROUP_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
)



CREATE TABLE ONGOING_OUTBREAKS_PHU(
	ID INT PRIMARY KEY IDENTITY (1,1),
	PHU_NUMNK INT, --NK
	ONGOING_OUTBREAKS_PHU_ID INT, --FK
	PHU_ID INT, --FK
	ONGOING_OUTBREAK_DATE DATETIME,
	NUMBER_ONGOING_OUTBREAKS INT,

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_ONGOING_OUTBREAKS_PHU_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),

	CONSTRAINT FK_ONGOING_OUTBREAKSPHU_PHU FOREIGN KEY (PHU_ID)
    REFERENCES PUBLIC_HEALTH_UNIT(ID),

	CONSTRAINT FK_ONGOING_OUTBREAKSPHU_OUTBREAKGROUP FOREIGN KEY (ONGOING_OUTBREAKS_PHU_ID)
    REFERENCES OUTBREAK_GROUP(ID),
)



CREATE TABLE AGE_GROUP(
	ID INT PRIMARY KEY IDENTITY (1,1),
	AGE_GROUP VARCHAR(35),
	--AGEGROUP_IDNK INT,

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_AGEGROUP_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
)



CREATE TABLE VACCINES_BY_AGE_PHU(
	ID INT PRIMARY KEY IDENTITY (1,1),
	PHU_IDNK INT,
	PHU_ID INT, --FK
	INJECT_DATE DATETIME,
	AGEGROUP_ID INT, --FK
	AT_LEAST_ONE_DOSE_CUMULATIVE INT,
	SECOND_DOSE_CUMULATIVE INT,
	FULL_VACCINATED_CUMULATIVE INT,
	THIRD_DOSE_CUMULATIVE INT,

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK

	CONSTRAINT FK_VACCBYAGE_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),

	CONSTRAINT FK_VACCBYAGE_PHU FOREIGN KEY (PHU_ID)
    REFERENCES PUBLIC_HEALTH_UNIT(ID),

	CONSTRAINT FK_VACCBYAGE_AGEGROUP FOREIGN KEY (AGEGROUP_ID)
    REFERENCES AGE_GROUP(ID),
)



CREATE TABLE GENDER(
	ID INT PRIMARY KEY IDENTITY (1,1),
	GENDER VARCHAR(20),

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK
	CONSTRAINT FK_GENDER_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
)



CREATE TABLE OUTCOME(
	ID INT PRIMARY KEY IDENTITY (1,1),
	OUTCOME VARCHAR(15),

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT --FK
	CONSTRAINT FK_OUTCOME_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
)



CREATE TABLE EXPOSURE(
	ID INT PRIMARY KEY IDENTITY (1,1),
	EXPOSURE VARCHAR(50),

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT, --FK
	CONSTRAINT FK_EXPOSURE_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),
)



CREATE TABLE COVID19_CASESREPORT_DETAIL(
	ID INT PRIMARY KEY IDENTITY (1,1),
	ROW_IDNK INT, --FROM SOURCE

	PHU_ID INT, --FK
	AGEGROUP_ID INT, --FK
	GENDER_ID INT, --FK
	OUTCOME_ID INT, --FK
	EXPOSURE_ID INT, --FK

	CASEREPORTED DATETIME,
	SPECIMENDATE DATETIME,
	TESTREPORTED DATETIME,
	ACCURATEEPISODE DATETIME,
	OUTBREAKRELATED VARCHAR(3), 

	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	SOURCE_ID INT --FK

	CONSTRAINT FK_CASESREPORT_SOURCE FOREIGN KEY (SOURCE_ID)
    REFERENCES SOURCE(SOURCE_ID),

	CONSTRAINT FK_CASESREPORT_AGEGROUP FOREIGN KEY (AGEGROUP_ID)
    REFERENCES AGE_GROUP(ID),

	CONSTRAINT FK_CASESREPORT_PHU FOREIGN KEY (PHU_ID)
    REFERENCES PUBLIC_HEALTH_UNIT(ID),

	CONSTRAINT FK_CASESREPORT_GENDER FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER(ID),

	CONSTRAINT FK_CASESREPORT_OUTCOME FOREIGN KEY (OUTCOME_ID)
    REFERENCES OUTCOME(ID),

	CONSTRAINT FK_CASESREPORT_EXPOSURE FOREIGN KEY (EXPOSURE_ID)
    REFERENCES EXPOSURE(ID),
)
GO

--CREATE CONSTRAINT
INSERT INTO SOURCE(SOURCE_NAME,CREATED_DATE,UPDATED_DATE)
VALUES('Ontario',getdate(),getdate())

use master
go


use NDSCovid19
go
