use NDSCovid19
GO
--ALTER TABLE PHU_GROUP DROP CONSTRAINT FK_GROUP_SOURCE;

--ALTER TABLE PHU_CITY DROP CONSTRAINT FK_CITY_SOURCE;
--ALTER TABLE PHU_CITY DROP CONSTRAINT FK_PHUCITY_PHUGROUP;

--ALTER TABLE PHU_ADDRESS DROP CONSTRAINT FK_PHUADDRESS_PHUCITY;
--ALTER TABLE PHU_ADDRESS DROP CONSTRAINT FK_PHUADDRESS_SOURCE;

--ALTER TABLE PUBLIC_HEALTH_UNIT DROP CONSTRAINT FK_PHU_PHUADDRESS;
--ALTER TABLE PUBLIC_HEALTH_UNIT DROP CONSTRAINT FK_PHU_SOURCE;

--ALTER TABLE OUTBREAK_GROUP DROP CONSTRAINT FK_OUTBREAKGROUP_SOURCE;

--ALTER TABLE ONGOING_OUTBREAKS_PHU DROP CONSTRAINT FK_ONGOING_OUTBREAKSPHU_OUTBREAKGROUP;
--ALTER TABLE ONGOING_OUTBREAKS_PHU DROP CONSTRAINT FK_ONGOING_OUTBREAKSPHU_PHU;
--ALTER TABLE ONGOING_OUTBREAKS_PHU DROP CONSTRAINT FK_ONGOING_OUTBREAKS_PHU_SOURCE;

--ALTER TABLE AGE_GROUP DROP CONSTRAINT FK_AGEGROUP_SOURCE;


Drop table SOURCE
Drop table PHU_GROUP
Drop table PHU_CITY
Drop table PHU_ADDRESS
Drop table PUBLIC_HEALTH_UNIT
Drop table OUTBREAK_GROUP
Drop table ONGOING_OUTBREAKS_PHU
Drop table AGE_GROUP
Drop table VACCINES_BY_AGE_PHU
Drop table GENDER
Drop table OUTCOME
Drop table EXPOSURE
Drop table COVID19_CASESREPORT_DETAIL