-- NEW VERSION --
use master
go


create database StageCOVID19
go

use StageCOVID19
go

CREATE TABLE CASESREPORT_STAGE (
    OUTCOME VARCHAR(25),
    AGE VARCHAR(50),
    GENDER VARCHAR(15),
    REPORTING_PHU VARCHAR(250),
    SPECIMENDATE DATE,
    CASEREPORTED_DATE DATE,
    PHUCITY VARCHAR(55),
    TESTREPORTED_DATE DATE,
    CASEACQUISITION_INFO VARCHAR(25),
    ACCURATEEPISODE_DT DATE,
    PHU_ADDRESS VARCHAR(30),
    PHU_WEBSITE VARCHAR(250),
    OUTBREAKRELATED VARCHAR(3),
    PHU_LATITUDE REAL,
    PHU_LONGITUDE REAL,
    PHU_POSTAL_CODE VARCHAR(7)
)


CREATE TABLE COMPILED_COVID19_CASE_DETAILS_CANADA_STAGE (
    ROW_ID INT,
    HEALTH_REGION VARCHAR(150),
    AGE_GROUP VARCHAR(25),
    GENDER VARCHAR(15),
    EXPOSURE VARCHAR(45),
    CASE_STATUS VARCHAR(15),
    DATE_REPORTED DATETIME,
    PROVINCE VARCHAR(35),
)


CREATE TABLE ONGOING_OUTBREAKS_PHU_STAGE (
    DATE DATE,
    PHU_NUM INT,
    OUTBREAK_GROUP VARCHAR(35),
    NUMBER_ONGOING_OUTBREAKS INT
)

CREATE TABLE VACCINES_BY_AGE_PHU_STAGE (
    DATE DATE,
    PHU_ID INT,
    AGEGROUP VARCHAR(150),
    AT_LEAST_ONE_DOSE_CUMULATIVE INT,
    SECOND_DOSE_CUMULATIVE INT,
    FULLY_VACCINATED_CUMULATIVE INT,
    THIRD_DOSE_CUMULATIVE INT
)


CREATE TABLE PUBLIC_HEALTH_UNIT_STAGE (
    REPORTING_PHU_LATITUDE FLOAT,
    REPORTING_PHU_LONGITUDE FLOAT,
    PHU_ID INT,
    REPORTING_PHU_ADDRESS VARCHAR(255),
    REPORTING_PHU VARCHAR(255),
    REPORTING_PHU_CITY VARCHAR(255),
    REPORTING_PHU_WEBSITE VARCHAR(255),
    REPORTING_PHU_POSTAL_CODE VARCHAR(255),
)

CREATE TABLE PUBLIC_HEALTH_UNITS_GROUP_STAGE (
    PHU_GROUP VARCHAR(250),
    PHU_CITY VARCHAR(250),
    PHU_REGION VARCHAR(250)
)